[workspace]

members = [
    "members/controller",
    "members/view",
    "members/web",
    "members/model",
    "members/repository",
    "members/message_broker",
    "members/read_model",
    "members/events"
]