[config]
default_to_workspace = false

[tasks.install]
command = "./install.sh"
args = [""]

[tasks.migrate]
dependencies = [
    { name = "migrate", path= "./members/repository"}
]

[tasks.redo-migrate]
dependencies = [
    { name = "redo-migrate", path= "./members/repository"}
]

[tasks.setup-db]
dependencies = [
    { name = "setup-db", path= "./members/repository"}
]