[config]
default_to_workspace = false

[tasks.install]
command = "./install.sh"
args = [""]

[tasks.migrate]
env = { CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = ["members/repository"]}

[tasks.redo-migrate]
env = { CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = ["members/repository"]}

[tasks.setup-db]
env = { CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = ["members/repository"]}
