[tasks.install]
command = "./install.sh"
args = [""]

[tasks.migrate]
command = "diesel"
workspace = false
args = ["migration", "run"]

[tasks.redo_migrate]
command = "diesel"
workspace = false
args = ["migration", "redo"]

