[config]
default_to_workspace = false

[tasks.install]
command = "./install.sh"
args = [""]

[tasks.migrate]
dependencies = [
    { name = "migrate", path= "./members/repository"}
]

[tasks.redo-migrate]
dependencies = [
    { name = "redo-migrate", path= "./members/repository"}
]

[tasks.setup-db]
dependencies = [
    { name = "setup-db", path= "./members/repository"}
]

[tasks.reset-db]
dependencies = [
    { name = "reset-db", path= "./members/repository"}
]

[tasks.run-read-model]
command = "cargo"
args = ["run", "-p", "read_model"]

[tasks.run-web]
command = "cargo"
args = ["run", "-p", "web-server"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.run-docker]
command = "docker-compose"
args = ["up"]
