[package]
name = "web-server"
version = "0.1.0"
edition = "2021"

[dependencies]
controller ={ path="../controller" }
repository = {path = "../repository"}
anyhow = "1.0"
actix-web = "4.2"
async-graphql={version="4", features = ["chrono"]}
async-graphql-actix-web="4"
chrono="0.4.23"