[tasks.setup-db]
command = "diesel"
workspace = true
args = ["setup"]

[tasks.migrate]
command = "diesel"
workspace = true
args = ["migration", "run"]

[tasks.redo-migrate]
command = "diesel"
workspace = true
args = ["migration", "redo", "--all"]

[tasks.new-migration]
command = "diesel"
workspace = true
args = ["migration", "generate", "${@}"]
