[tasks.setup-db]
command = "diesel"
workspace = true
env = { CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = ["repository"]}
args = ["setup"]

[tasks.migrate]
command = "diesel"
workspace = true
env = { CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = ["repository"]}
args = ["migration", "run"]

[tasks.redo-migrate]
command = "diesel"
workspace = true
env = { CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = ["repository"]}
args = ["migration", "redo"]